version: 2

defaults: &build
  docker:
    - image: circleci/python:3.6.6
      environment:
        DATABASE_URL: mysql://root@127.0.0.1/rtalib_test_db
    - image: circleci/mysql:5.7.23-ram
      environment:
        MYSQL_ALLOW_EMPTY_PASSWORD: true
        MYSQL_DATABASE: rtalib_test_db
        MYSQL_HOST: 127.0.0.1
        MYSQL_USER: root
    - image: circleci/redis:4.0.10-stretch

  steps:
    - checkout
    - restore_cache:
        keys:
          - hiredis-deps-

    - run:
        name: Installng hiredis dependencies
        command: |
          cd External_Libraries_Building_Area
          echo Hiredis installing ...
          git clone https://github.com/redis/hiredis.git
          cd hiredis
          export PREFIX=~/cxx-rtalib-circleci/CxxRTAlib_External_Dependencies_Installed/
          make
          echo Hiredis installed.

    - save_cache:
            key: hiredis-deps
            paths:
              - External_Libraries_Building_Area/hiredis

    - restore_cache:
        keys:
          - cmake-deps-

    - run:
        name: Installng cmkae dependencies
        command: |
          cd ~/cxx-rtalib-circleci/External_Libraries_Building_Area
          echo Bootstrap installing ...
          wget https://cmake.org/files/v3.13/cmake-3.13.0-rc1.tar.gz
          tar -zxvf cmake-3.13.0-rc1.tar.gz
          cd cmake-3.13.0-rc1
          ./bootstrap --prefix=~/cxx-rtalib-circleci/CxxRTAlib_External_Dependencies_Installed/cmake-3.13.0
          make
          make install
          echo Bootstrap installed.

    - save_cache:
            key: cmake-deps-
            paths:
              - External_Libraries_Building_Area/cmake-3.13.0


    - restore_cache:
        keys:
          - boost-deps-

    - run:
        name: Installing boost dependencies
        command: |
          cd ~/cxx-rtalib-circleci/External_Libraries_Building_Area
          echo Boost installing ...
          wget https://dl.bintray.com/boostorg/release/1.67.0/source/boost_1_67_0.tar.bz2
          tar --bzip2 -xf boost_1_67_0.tar.bz2
          cd boost_1_67_0/tools/build
          ./bootstrap.sh --prefix=~/cxx-rtalib-circleci/CxxRTAlib_External_Dependencies_Installed/
          echo Boost installed.

    - save_cache:
            key: boost-deps-
            paths:
              - External_Libraries_Building_Area/


jobs:
  CxxRTAlibTest:
    <<: *build
    working_directory: ~/cxx-rtalib-circleci
    steps:
      - checkout
      - run:
          name: Installing mysql-client
          command: sudo apt install -y mysql-client
      - run:
          name: install dockerize
          command: wget https://github.com/jwilder/dockerize/releases/download/$DOCKERIZE_VERSION/dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz && sudo tar -C /usr/local/bin -xzvf dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz && rm dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz
          environment:
            DOCKERIZE_VERSION: v0.3.0
      - run:
          name: Wait for db
          command: dockerize -wait tcp://127.0.0.1:3306 -timeout 1m
      - run:
          name: Executing sql script to initialize db
          command: |
            DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null && pwd )"
            sudo mysql -h 127.0.0.1 -u root  -v < $DIR/PyRTAlib/TestEnvironment/setup/setup_test_db_circleci.sql
      - run:
          name: Creating the rtalibconfig configuration file
          command: |
            DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null && pwd )"
            echo "[General]
            modelname=rtalib_dl_test_table
            mjdref=50000
            debug=no
            batchsize=1
            numberofthreads=1

            [Dtr]
            active=no
            debug=yes
            inputchannel=dtr.input
            outputchannel=dtr.output

            [MySql]
            host=127.0.0.1
            username=rtalib_test_user
            password=x1x2x3
            dbname=rtalib_test_db

            [Redis]
            host=127.0.0.1
            password=
            dbname=1
            indexon=rtalib_dl_test_table:timerealtt,rtalib_test_table:a

            [MySqlPipelineDatabase]
            active=no
            debug=no
            host=
            username=
            password=
            dbname=
            " > $DIR/CxxRTAlib/TestEnvironment/rtalibconfig
      - run:
          name: Creating folder for test results
          command: |
            mkdir ~/cxx-rtalib-circleci/test_artifacts
            touch ~/cxx-rtalib-circleci/test_artifacts/cxx_test_result.txt

      - run:
          name: Creating folder for externale libreries
          command: |
            mkdir ~/cxx-rtalib-circleci/External_Libraries_Building_Area
            mkdir ~/cxx-rtalib-circleci/CxxRTAlib_External_Dependencies_Installed


      - run:
          name: CxxRTAlib testing
          command: |
            echo CxxRTAlib test started!!


workflows:
  version: 2
  pyrtalib_circleci_test:
    jobs:
      - CxxRTAlibTest
