version: 2

jobs:
  CxxRTAlibTest:

    working_directory: ~/cxx-rtalib-circleci

    docker:
      - image: circleci/python:3.6.6
        environment:
          DATABASE_URL: mysql://root@127.0.0.1/rtalib_test_db
      - image: circleci/mysql:5.7.23-ram
        environment:
          MYSQL_ALLOW_EMPTY_PASSWORD: true
          MYSQL_DATABASE: rtalib_test_db
          MYSQL_HOST: 127.0.0.1
          MYSQL_USER: root
      - image: circleci/redis:4.0.10-stretch


    steps:
      - checkout
      - run:
          name: Installing mysql-client
          command: sudo apt install -y mysql-client
      - run:
          name: install dockerize
          command: wget https://github.com/jwilder/dockerize/releases/download/$DOCKERIZE_VERSION/dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz && sudo tar -C /usr/local/bin -xzvf dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz && rm dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz
          environment:
            DOCKERIZE_VERSION: v0.3.0
      - run:
          name: Wait for db
          command: dockerize -wait tcp://127.0.0.1:3306 -timeout 1m
      - run:
          name: Executing sql script to initialize db
          command: |
            DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null && pwd )"
            sudo mysql -h 127.0.0.1 -u root  -v < $DIR/PyRTAlib/TestEnvironment/setup/setup_test_db_circleci.sql
      - run:
          name: Creating the rtalibconfig configuration file
          command: |
            DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null && pwd )"
            echo "[General]
            modelname=rtalib_dl_test_table
            mjdref=50000
            debug=no
            batchsize=1
            numberofthreads=1

            [Dtr]
            active=no
            debug=yes
            inputchannel=dtr.input
            outputchannel=dtr.output

            [MySql]
            host=127.0.0.1
            username=rtalib_test_user
            password=x1x2x3
            dbname=rtalib_test_db

            [Redis]
            host=127.0.0.1
            password=
            dbname=1
            indexon=rtalib_dl_test_table:timerealtt,rtalib_test_table:a

            [MySqlPipelineDatabase]
            active=no
            debug=no
            host=
            username=
            password=
            dbname=
            " > $DIR/CxxRTAlib/TestEnvironment/rtalibconfig
      - run:
          name: Creating folder for external libreries
          command: |
            mkdir ~/cxx-rtalib-circleci/External_Libraries_Building_Area
            mkdir ~/cxx-rtalib-circleci/CxxRTAlib_External_Dependencies_Installed
      - restore_cache:
          keys:
            - cxxrtalic-hiredis-cache
      - run:
          name: Installng hiredis dependencies
          command: |
            cd ~/cxx-rtalib-circleci/External_Libraries_Building_Area
            if [ ! -f ~/cxx-rtalib-circleci/External_Libraries_Building_Area/hiredis/libhiredis.a ]; then
            echo Installing Hiredis ...
            git clone https://github.com/redis/hiredis.git && cd hiredis
            make
            echo Hiredis installed!
            fi
      - save_cache:
              key: cxxrtalic-hiredis-cache
              paths:
                - ~/cxx-rtalib-circleci/External_Libraries_Building_Area/hiredis

      - restore_cache:
          keys:
            - cxxrtalic-cmake-3.12.3-cache
      - run:
          name: Installng cmake dependencies
          command: |
            cd ~/cxx-rtalib-circleci/External_Libraries_Building_Area
            if [ ! -d ~/cxx-rtalib-circleci/CxxRTAlib_External_Dependencies_Installed/cmake-3.12.3 ]; then
            echo Bootstrap installing ...
            wget https://cmake.org/files/v3.12/cmake-3.12.3.tar.gz
            tar -zxvf cmake-3.12.3.tar.gz
            cd cmake-3.12.3
            ./bootstrap --prefix=~/cxx-rtalib-circleci/CxxRTAlib_External_Dependencies_Installed/cmake-3.12.3
            make
            make install

            echo Bootstrap installed.
            fi
      - save_cache:
              key: cxxrtalic-cmake-3.12.3-cache
              paths:
                - ~/cxx-rtalib-circleci/CxxRTAlib_External_Dependencies_Installed/cmake-3.12.3

      - restore_cache:
          keys:
            - cxxrtalic-boost-1-67-0-cache
      - run:
          name: Installng Boost dependencies
          command: |
            cd ~/cxx-rtalib-circleci/External_Libraries_Building_Area
            if [ ! -d ~/cxx-rtalib-circleci/External_Libraries_Building_Area/boost_1_67_0 ]; then
            echo Boost installing ...
            wget https://dl.bintray.com/boostorg/release/1.67.0/source/boost_1_67_0.tar.bz2
            tar --bzip2 -xf boost_1_67_0.tar.bz2
            cd boost_1_67_0/tools/build
            ./bootstrap.sh
            ./b2 install --prefix=~/cxx-rtalib-circleci/CxxRTAlib_External_Dependencies_Installed/boost_1_67_0
            echo Boost installed.
            fi
      - save_cache:
              key: cxxrtalic-boost-1-67-0-cache
              paths:
                - ~/cxx-rtalib-circleci/External_Libraries_Building_Area/boost_1_67_0

      - restore_cache:
          keys:
            - cxxrtalic-mysql-cxx-connector-cache
      - run:
          name: Installng mysqlcppconnector dependencies
          command: |
            cd ~/cxx-rtalib-circleci/External_Libraries_Building_Area
            if [ ! -d ~/cxx-rtalib-circleci/CxxRTAlib_External_Dependencies_Installed/mysql-connector-cpp-install ]; then
            echo MySql connector cpp installing ...
            git clone https://github.com/mysql/mysql-connector-cpp.git
            mkdir ~/cxx-rtalib-circleci/CxxRTAlib_External_Dependencies_Installed/mysql-connector-cpp-install
            mkdir ~/cxx-rtalib-circleci/External_Libraries_Building_Area/mysql-connector-cpp-build
            cd mysql-connector-cpp
            git checkout 8.0
            cd ../mysql-connector-cpp-build
            /home/circleci/cxx-rtalib-circleci/CxxRTAlib_External_Dependencies_Installed/cmake-3.12.3/bin/cmake -DCMAKE_POLICY_DEFAULT_CMP0022=NEW -DCMAKE_INSTALL_PREFIX=~/cxx-rtalib-circleci/CxxRTAlib_External_Dependencies_Installed/mysql-connector-cpp-install -DBOOST_ROOT=~/cxx-rtalib-circleci/External_Libraries_Building_Area/boost_1_67_0 ~/cxx-rtalib-circleci/External_Libraries_Building_Area/mysql-connector-cpp
            make
            make install
            echo MySql connector cpp installed.
            fi
      - save_cache:
              key: cxxrtalic-mysql-cxx-connector-cache
              paths:
                - ~/cxx-rtalib-circleci/CxxRTAlib_External_Dependencies_Installed/mysql-connector-cpp-install

      - run:
          name: Creating folder for test results
          command: |
            mkdir ~/cxx-rtalib-circleci/test_artifacts
            touch ~/cxx-rtalib-circleci/test_artifacts/cxx_test_result.txt

      - run:
          name: Installing CxxRTAlib
          command: |
            cd ~/cxx-rtalib-circleci/CxxRTAlib
            echo 'export MYSQL_CXX_CNT="~/cxx-rtalib-circleci/CxxRTAlib_External_Dependencies_Installed/mysql-connector-cpp-install/"' >> $BASH_ENV
            echo 'export BOOST_PATH="~/cxx-rtalib-circleci/External_Libraries_Building_Area/boost_1_67_0"' >> $BASH_ENV
            echo 'export REDIS="~/cxx-rtalib-circleci/External_Libraries_Building_Area/hiredis/"' >> $BASH_ENV
            echo 'export LD_LIBRARY_PATH="~/cxx-rtalib-circleci/CxxRTAlib_External_Dependencies_Installed/mysql-connector-cpp-install:$LD_LIBRARY_PATH"' >> $BASH_ENV
            echo 'export LD_LIBRARY_PATH="~/cxx-rtalib-circleci/External_Libraries_Building_Area/hiredis:$LD_LIBRARY_PATH"' >> $BASH_ENV
            make


workflows:
  version: 2
  pyrtalib_circleci_test:
    jobs:
      - CxxRTAlibTest
