# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  build:
    working_directory: ~/rtalib-circleci-testing
    docker:
      - image: circleci/python:3.6.6
        environment:
          PIPENV_VENV_IN_PROJECT: true
          DATABASE_URL: mysql://root@localhost/rtalib_test_db
      - image: circleci/mysql:8.0.11-ram
        environment:
          MYSQL_USER: root
          MYSQL_DB: rtalib_test_db
    

    steps:
      - checkout    #  By default, source code is checked out to the path specified by working_directory
      - run:
          command: |  # use pipenv to install dependencies
            sudo pip install pipenv
            pipenv install
     - run:
          command: |
            echo "Test!!"

      
          

